run:
  skip-files:
  - doc.go
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - errcheck
    - errname
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - godot
    - gosec
    - grouper
    - interfacebloat
    - makezero
    - revive
    - unconvert
    - wsl
linters-settings:
  funlen:
    lines: -1
    statements: 60

  grouper:
    const-require-grouping: true
    import-require-single-import: true
    import-require-grouping: true
    type-require-grouping: true
    var-require-grouping: true
  
  gci:
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(go.breu.io/temporal-tools) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all imports that could not be matched to another section type.
    # Default: true
    skip-generated: false
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    custom-order: true

  # gocritic:
  #   disabled-checks:
  #     - ruleguard               # unused
  
  dogsled:
    # Checks assignments with too many blank identifiers.
    # Default: 2
    max-blank-identifiers: 3
  
  interfacebloat:
    max: 15
  
  revive:
    confidence: 0.8
    rules:
      - name: line-length-limit
        severity: warning
        arguments:
          - 140
      - name: use-any
        severity: warning

