version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - errname
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godot
    - gosec
    - grouper
    - interfacebloat
    - makezero
    - revive
    - unconvert
    - wsl_v5
  settings:
    dogsled:
      max-blank-identifiers: 3
    funlen:
      lines: -1
      statements: 60
    grouper:
      const-require-grouping: true
      import-require-single-import: true
      import-require-grouping: true
      type-require-grouping: true
      var-require-grouping: true
    interfacebloat:
      max: 15
    revive:
      confidence: 0.8
      rules:
        - name: line-length-limit
          arguments:
            - 140
          severity: warning
        - name: use-any
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - doc\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(go.breu.io/durex)
        - blank
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - doc\.go$
      - third_party$
      - builtin$
      - examples$
